force-app/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/objects/Equipment_Maintenance_Item__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
        <relationshipName>Equipment_Maintenance_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Equipment Maintenance Items</relationshipLabel>
        <relationshipName>Equipment_Maintenance_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Equipment Maintenance Item</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/classes/MaintenanceRequestHelper.cls
public with sharing class MaintenanceRequestHelper {

    public static void updateWorkOrders(List<Case> oldRequests, List<Case> newRequests) {
        List<Case> newListRequest = new List<Case>();
        System.debug('newRequests:' + newRequests);

        List<Equipment_Maintenance_Item__c> currentMaintenanceList =
        [SELECT Id, Maintenance_Request__c, Equipment__r.Maintenance_Cycle__c FROM Equipment_Maintenance_Item__c WHERE Maintenance_Request__c IN :newRequests];

        Map<Id, Integer> mapDueDate = getMapDueDate(currentMaintenanceList);

        for(Case updatedRequest : newRequests) {
            //Check if new case type = Repair/Routine Maintenance and status = Closed, proceed
            if((updatedRequest.Type == 'Repair' || updatedRequest.Type == 'Routine Maintenance') && updatedRequest.Status == 'Closed') {
                Case newRequestRoutine = new Case();
                newRequestRoutine.Vehicle__c = updatedRequest.Vehicle__c;
                newRequestRoutine.Subject = 'Routine created by Ana';
                newRequestRoutine.Type = 'Routine Maintenance';
                newRequestRoutine.Date_Reported__c = Date.today();
                newRequestRoutine.Date_Due__c = mapDueDate.get(updatedRequest.Id) != null ? Date.today() + mapDueDate.get(updatedRequest.Id) : Date.today();
                newRequestRoutine.ParentId = updatedRequest.Id;
                newListRequest.add(newRequestRoutine);
            }
        }
        insert newListRequest;

        List<Equipment_Maintenance_Item__c> listMaintenanceToUpdate = new List<Equipment_Maintenance_Item__c>();
        System.debug('currentItems for whole list:' + currentMaintenanceList);

        for(Case newRequestRoutine : newListRequest) {
            for(Equipment_Maintenance_Item__c existingMaintenance : currentMaintenanceList) {
                //si este caso q se actualiza tiene alguna request, el nuevo caso tendra lo mismo -> en la request, actualizar el padre
                if(newRequestRoutine.ParentId == existingMaintenance.Maintenance_Request__c) {
                    existingMaintenance.Maintenance_Request__c = newRequestRoutine.Id;
                    listMaintenanceToUpdate.add(existingMaintenance);
                }
            }
        }
        System.debug('listMaintenanceToUpdate:' + listMaintenanceToUpdate);
        update listMaintenanceToUpdate;
    }

    private static Map<Id, Integer> getMapDueDate(List<Equipment_Maintenance_Item__c> currentMaintenanceList) {
        Map<Id, Integer> mapDueDate = new Map<Id, Integer>();
        for(Equipment_Maintenance_Item__c maintenance : currentMaintenanceList) {
            if(mapDueDate.containsKey(maintenance.Maintenance_Request__c)) {
                Integer storedDueDate = mapDueDate.get(maintenance.Maintenance_Request__c);
                mapDueDate.put(maintenance.Maintenance_Request__c, Integer.valueOf(Math.min(maintenance.Equipment__r.Maintenance_Cycle__c, storedDueDate)));
            }
            else {
                mapDueDate.put(maintenance.Maintenance_Request__c, Integer.valueOf(maintenance.Equipment__r.Maintenance_Cycle__c));
            }
        }
        System.debug('mapDueDate:' + mapDueDate);
        return mapDueDate;
    }
}