force-app/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/classes/WarehouseCalloutService.cls
public with sharing class WarehouseCalloutService implements Queueable, Database.AllowsCallouts {

    private static final String WAREHOUSE_URL = 'https://th-superbadge-apex.herokuapp.com/equipment';

    public void execute(QueueableContext context) {
        //Make the REST Callout
        Http http = new Http();

        HttpRequest req = new HttpRequest();
        req.setEndpoint(WAREHOUSE_URL);
        req.setMethod('GET');

        HttpResponse response = http.send(req);
        List<HerokuParser> responseParserList = HerokuParser.parse(response.getBody());

        //Upsert Equipment records in Salesforce
        List<Product2> equipmentsToUpsert = new List<Product2>();
        for(HerokuParser equipmentRetrieved : responseParserList) {
            Product2 equipmToUpsert = new Product2();
            equipmToUpsert.Name = equipmentRetrieved.name;
            equipmToUpsert.Replacement_Part__c = true;
            equipmToUpsert.Cost__c = equipmentRetrieved.cost;
            equipmToUpsert.Current_Inventory__c = equipmentRetrieved.quantity;
            equipmToUpsert.Lifespan_Months__c = equipmentRetrieved.lifespan;
            equipmToUpsert.Maintenance_Cycle__c = equipmentRetrieved.maintenanceperiod;
            equipmToUpsert.Warehouse_SKU__c = equipmentRetrieved.sku;
            equipmentsToUpsert.add(equipmToUpsert);
        }

        upsert equipmentsToUpsert Warehouse_SKU__c;
    }
}